# Generated by Django 3.2.5 on 2021-07-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210715_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datetime',
        ),
    ]
