# Generated by Django 3.2.5 on 2021-08-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210819_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='photos',
            new_name='photo',
        ),
    ]
